// src/lib/components/footer.svelte
<script lang="ts">
  import Social from "$lib/components/social.svelte";

  export let content: Site;
</script>

<footer>
  <div class="container flow">
    <h2>{content.data.footerHeading}</h2>

    <div class="footer-content">
      <div>
        <h3>{content.data.footerEmail}</h3>
        <p>{content.data.footerLocation}</p>
        <Social
          instagram={content.data.instagram}
          linkedin={content.data.linkedin}
        />
      </div>

      <div>
        <h4>{content.data.footerSubHeading}</h4>
        <p>{content.data.footerDescription}</p>
      </div>
    </div>

    <div class="footer-copyright">
      <img src={content.data.logo} alt="Liam Johnston logo" />
      <p>{content.data.footerCopyright}</p>
    </div>
  </div>
</footer>

<style>
  footer {
    padding: var(--spacing-32);
    background-color: var(--colour-bg-muted);
  }

  footer > .flow {
    --flow-spacing: var(--spacing-40);
  }

  .footer-content {
    display: flex;
    gap: var(--spacing-60);
  }
  .footer-content > div {
    display: flex;
    flex-direction: column;
    gap: var(--spacing-32);
  }
  .footer-content > div:nth-child(1) > h3 {
    color: var(--colour-brand);
  }

  @media (max-width: 1064px) {
    .footer-content {
      flex-direction: column;
    }
    .footer-content > div {
      gap: var(--spacing-16);
    }
  }

  .footer-copyright {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: var(--spacing-16);
  }

  img {
    width: 6rem;
    height: 6rem;
  }
</style>

// src/components/footer.tsx
import Image from "next/image";
import { Site } from "@/utils/types";
import Social from "./social";

export default function Footer({ site }: { site: Site }) {
  return (
    <footer id='contact' className='mt-24 py-16 bg-slate-900'>
      <div className='container space-y-16'>
        <h2>{site.data.footerHeading}</h2>

        <div className='flex flex-col gap-16 lg:flex-row'>
          <div className='flex flex-col gap-6'>
            <h3 className='text-yellow-400'>{site.data.footerEmail}</h3>
            <p>{site.data.footerLocation}</p>
            <Social
              instagram={site.data.instagram}
              linkedin={site.data.linkedin}
            />
          </div>

          <div className='flex flex-col gap-6'>
            <h4>{site.data.footerSubHeading}</h4>
            <p>{site.data.footerDescription}</p>
          </div>
        </div>

        <div className='flex items-center justify-center gap-6'>
          <Image
            src={site.data.logo}
            alt='Liam Johnston logo'
            width={60}
            height={60}
          />
          <p>{site.data.footerCopyright}</p>
        </div>
      </div>
    </footer>
  );
}
