// src/lib/components/hero.svelte
<script lang="ts">
  export let heading: string;
  export let description: string;
  export let buttonText: string;
</script>

<section id="home" class="animate-fade-up">
  <div class="flow">
    <h1>{heading}</h1>
    <p>{description}</p>
    <a class="btn" href="#work">{buttonText}</a>
  </div>
</section>

<style>
  section {
    display: grid;
    place-items: center;
    text-align: center;
    padding: var(--spacing-section) 0;
  }

  p {
    max-width: 60ch;
    margin-inline: auto;
  }

  .flow {
    --flow-spacing: var(--spacing-32);
  }

  h1 {
    color: var(--colour-brand);
    border: 6px solid var(--colour-brand);
    padding: var(--spacing-20) var(--spacing-32);
    border-bottom-right-radius: var(--radius-base);
  }

  a {
    display: inline-block;
  }
</style>

// src/components/hero.tsx
import { FC } from "react";

const Hero: FC<{
  heading: string;
  description: string;
  buttonText: string;
}> = ({ heading, description, buttonText }) => {
  return (
    <section
      id='home'
      className='max-w-2xl mx-auto text-center animate-fade-up py-16 md:py-28'
    >
      <div className='space-y-12'>
        <h1 className='text-yellow-500 border-8 border-yellow-500 p-6 rounded-br-[4rem]'>
          {heading}
        </h1>
        <p>{description}</p>
        <a className='btn inline-block' href='#work'>
          {buttonText}
        </a>
      </div>
    </section>
  );
};

export default Hero;
