// src/lib/components/seo.svelte
<script lang="ts">
  import { page } from "$app/stores";
  export let title: string;
  export let description: string =
    "A Newcastle-Upon-Tyne based marketing designer currently looking for my next big role. I'm passionate about pushing the limits of brands through creative marketing strategies and striking design.";
  export let url: string;
</script>

<svelte:head>
  <title>{title} | Liam Johnston Creative Marketer</title>
  <meta name="description" content={description} />
  <meta
    name="keywords"
    content="Design, Marketing, Copywrighting, Graphic Design, Web, Mobile, Logo, Branding"
  />
  <link rel="canonical" href={`${$page.url.origin}${url}`} />
</svelte:head>

// src/components/seo.tsx
import Head from "next/head";
import { FC } from "react";
import { useRouter } from "next/router";

const SEO: FC<{ title?: string; description?: string }> = ({
  title,
  description
}) => {
  const router = useRouter();
  const canonical = "https://liamjohnston.vercel.app" + router.pathname;
  const titleMeta = title ? title : "Liam Johnston - Creative Marketer";
  const descriptionMeta = description
    ? description
    : "A Newcastle-Upon-Tyne based marketing designer currently looking for my next big role. I'm passionate about pushing the limits of brands through creative marketing strategies and striking design";

  return (
    <Head>
      <title>{titleMeta}</title>
      <meta name='description' content={descriptionMeta} />
      <meta
        name='keywords'
        content='Graphic Design, Marketing, Liam Johnston, Marketing Design'
      />
      <meta name='twitter:card' content='summary_large_image' />
      <meta name='twitter:site' content='liamjohnston' />
      <meta name='twitter:image' content='/images/me.png' />
      <meta name='og:site_name' content='Liam Johnston' />
      <meta name='og:type' content='website' />
      <meta name='og:image' content='/images/me.jpeg' />
      <meta name='og:url' content={canonical} />
      <meta name='og:title' content={titleMeta} />
      <meta name='og:description' content={descriptionMeta} />
      <link rel='canonical' href={canonical} />
      <link rel='icon' href='/images/logo.svg' />
    </Head>
  );
};

export default SEO;
